config/routes.rb
Rails.application.routes.draw do

devise_for :users,
             path: 'accounts',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                            registrations: 'registrations' }

  get 'users/dashboard'
  
  resources :users, only: [:index] do
    resource :timetable
    resources :listings, only: [:index, :new, :create]
  end

  resources :listings, only: [:show, :edit, :update, :destroy] do 
    resources :appointments, except: [:show]
  end

  resources :appointments, only: [:show] do
    resource :review
  end

  root 'welcome#beta_landing'  
  get 'teacher' => 'welcome#become_a_teacher'
  get 'search' => 'listings#search' 
  get 'nearby' => 'listings#nearby'
  
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  get '/users/:user_id/location', to: 'users#location', as: :user_location

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :appointments
	belongs_to :language
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :get_user, only: [:new, :create]

	def welcome_search
    @results = Listing.where(language_id: params[:language_id], 
      user_id: User.where(location: params[:location])).includes(user: [:reviews]).paginate(:page => params[:page], :per_page => 10)
	end

  def index
  	@listings = Listing.all
  end

  def nearby
    if params[:search].present?
      @results = Listing.where(user_id: Teacher.near(params[:search]).map do |t| t.id end).includes(user: [:reviews]).paginate(:page => params[:page], :per_page => 10)
      @languages = Language.all
      @locations = Teacher.uniq.pluck(:location)
      @hash = Gmaps4rails.build_markers(@results) do |listing, marker|
        marker.lat listing.user.latitude
        marker.lng listing.user.longitude
      end
      render 'search'
    else
      @results = Listing.all.includes(user: [:reviews]).paginate(:page => params[:page], :per_page => 10)
      @hash = Gmaps4rails.build_markers(@results) do |listing, marker|
        marker.lat listing.user.latitude
        marker.lng listing.user.longitude
      end     
      @languages = Language.all
      @locations = Teacher.uniq.pluck(:location)
      render 'search'
    end
  end

  def search
    # Add Complex Filtering based on
    # from, location,
    # language_id, price, platform, is_trial

  	#Refactor for one query
  	@results = welcome_search
    @languages = Language.all
    @locations = Teacher.uniq.pluck(:location)
    @hash = Gmaps4rails.build_markers(@results) do |listing, marker|
      marker.lat listing.user.latitude
      marker.lng listing.user.longitude
    end
  	# Add Filtering based on
  	# from, location,
  	# language_id, price, platform, is_trial
  end

  def new
    @listing = @user.listings.new
    @languages = Language.all.collect { |l| [l.name, l.id] }
  end

  def create
    @listing = @user.listings.new(listing_params)

    if @listing.save
      redirect_to users_dashboard_path
    else
      render 'new'
    end
  end

  def edit
    @listing = Listing.find(params[:id])
    @languages = Language.all.collect { |l| [l.name, l.id] }
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to users_dashboard_path
    else
      render 'edit'
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @appointment = @listing.appointments.new
    @user = @listing.user
  end

    private

    def get_user
      @user = User.find(params[:user_id])
    end

    def listing_params
      params.require(:listing).permit(:description, :is_trial, :price, :video_url, :platform, :language_id)
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<%= form_for(@listing,:html=>{:name=>"f",:onsubmit=>"return youtube_parser();"}) do |f| %>
	  <div class="form-group">
	  	<%= f.label :description %>
	    <%= f.text_field :description, class: "form-control" %>
	  </div>				  
	  <div class="form-group">
	  	<%= f.label :is_trial %>
	    <%= f.check_box :is_trial %>
	  </div>
		Video Url:<input type="text" id="listing_video_url">
	  <%= f.hidden_field :video_url, id: 'video_id' %>
	  <div class="form-group">
	  	<%= f.label :price %>
	    <%= f.number_field :price, class: "form-control" %>
	  </div>
	  <div class="form-group">
	  	<%= f.label :platform %>
	    <%= f.text_field :platform, class: "form-control" %>
	  </div>
	  <div class="form-group">
	  	<label for="language_id">Select Language</label>
	    <%= f.select :language_id, @languages , class: "form-control" %>
	  </div>	  
      <%= f.submit "Submit" %>
<%  end %>


<script>

function youtube_parser(){
	var url = $('#listing_video_url').val();
    var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#\&\?]*).*/;
    var match = url.match(regExp);
    if(match&&match[7].length==11){
    	$('#video_id').val('<iframe class= "embed-responsive-item" src="//www.youtube.com/embed/' + match[7] + '"></iframe>');
    	return true;
    } else { 
    	return false;
    }
}



</script>

app/views/listings/index.html.erb
<h1>Listings#index</h1>
<p>Find me in app/views/listings/index.html.erb</p>

app/views/listings/new.html.erb
<h1>Listings#new</h1>
<%= form_for([ @user, @listing], url: user_listings_path(@user)) do |f| %>
	  <div class="form-group">
	  	<%= f.label :description %>
	    <%= f.text_field :description, class: "form-control" %>
	  </div>				  
	  <div class="form-group">
	  	<%= f.label :is_trial %>
	    <%= f.check_box :is_trial %>
	  </div>
	  <div class="form-group">
	  	<%= f.label :video_url %>
	    <%= f.text_field :video_url, class: "form-control"%>
	  </div>
	  <div class="form-group">
	  	<%= f.label :price %>
	    <%= f.number_field :price, class: "form-control" %>
	  </div>
	  <div class="form-group">
	  	<%= f.label :platform %>
	    <%= f.text_field :platform, class: "form-control" %>
	  </div>
	  <div class="form-group">
	  	<label for="language_id">Select Language</label>
	    <%= f.select :language_id, @languages , class: "form-control" %>
	  </div>	  
      <%= f.submit "Submit" %>
<%  end %>

app/views/listings/search.html.erb
<div id="search-results">
	<%= render "shared/navbar" %>
	<div class="container">
		<div class="search-intro">
			<%= image_tag "search.svg", class: "howitworks-icon", width: '110px', height: '110px' %>
			<div class="search-intro-text">
				<h1>Öğretmen bul</h1>
				<p>İstediğin konuda, online veya birebir ders veren öğretmen bul. Seçtiğin kriterlere en uygun öğretmenleri listele, sana en uygun öğretmen ile iletişime geç.</p>
			</div>
		</div>	

		<div class="search-filters">
			<div class="top-filters">
	      <%= form_tag nearby_path, :method => :get, class:"form-inline" do %>
	        <p>
	          <%= text_field_tag :search, params[:search],:id => 'geo-input', class: "form-control filters-location-input", placeholder: "Konum giriniz" %>
	          <%= select_tag :language_id, 
	                options_for_select(@languages.collect{ |l| [l.name, l.id] }), 
	                class: "form-control filters-lesson-input",prompt: "Ders seçiniz" %>
	          <%= submit_tag "EĞİTMEN ARA", :name => nil, class: "btn btn-filters-search" %>
	          </p>
	      <% end %>
			</div>
			<div class="secondary-filters">
				<div class="availability-filter">
					<p>Uygunluk</p>
	        <%= select_tag "availability", 
	              "<option>Sabah</option><option>Öğle</option><option>Akşam</option><option>Gece</option><option>Haftasonu</option>".html_safe,prompt: "Seçiniz", class: "btn availability-select" %>		
				</div>
				<div class="price-range-filter">
					<p>
					  <label for="amount">Saatlik ücret:</label>
					  <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
					</p>
					 
					<div id="slider-range"></div>		
				</div>
				<div class="platform-filter">
					<p>Platform</p>
					<%= select_tag "platform", options_for_select([ "Online", "Lokal", "Hepsi" ], "Hepsi"), class: "btn platform-select" %>					
				</div>
				<div class="sort">
					Sırala:
					<a href="#">Puan</a>
					<a href="#">Uzaklık</a>
				</div>
			</div>
		</div>   <!-- search-filters -->

		<div id="listing-results">
			<% @results.each do |a| %>
				<div class="well well-lg">
					<%= image_tag "profile3.jpg", class: "listing-avatar", width: '150px', height: '150px' %>
					<span class="name"><%= "#{a.user.first_name} #{a.user.last_name}" %></span><span id="average_rating_<%=a.user.id%>"></span> (<%= a.user.reviews.count %>)<br>
					<%= truncate(a.description, length: 250) %><br>
					<span class="price-label">Price:</span><span class="price"><%= " #{a.price} $" %></span><br>
					<%= link_to "View Schedule", listing_path(a), class: "btn btn-schedule" %>
					<% if current_user %>
						<%= link_to "Send Message", '#', "data-toggle" => "modal", "data-target" => "#MessageModal#{a.user.id}",class: "btn btn-message" %>
						  <div id="MessageModal<%=a.user.id%>" class="auth-modal modal" role="dialog">
						    <div class="modal-dialog">

						      <!-- Modal content-->
						      <div class="modal-content"> 
						        <div class="modal-body">
						          <%= form_tag messages_path(to: a.user.id), method: :post do %>
						            <div class="form-group">
						              <%= label_tag 'message[subject]', 'Subject' %>
						              <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
						            </div>

						            <div class="form-group">
						              <%= label_tag 'message[body]', 'Message' %>
						              <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
						            </div>
						            <%= submit_tag 'Send', class: 'btn btn-primary' %>
						          <% end %>      
						        </div>
						        <a href="#" class="modal-close" data-dismiss="modal">X</a>
						      </div>
						    </div>
						  </div> <!-- MessageModal -->
					<% else %>
						<%= link_to "Send Message", '#', "data-toggle" => "modal", "data-target" => "#ModalSignUp",class: "btn btn-message" %>
					<% end %>			
				</div>
				<script>
					$('#average_rating_<%=a.user.id%>').raty({
						path: '',
						readOnly: true,
						score: <%= a.user.average_rating %>
					});
				</script>
			<% end %>			
		</div>


	</div>  <!-- container -->

	<%= will_paginate @results, renderer: BootstrapPagination::Rails %>
</div>

 <script>
  $(document).ready(function() {
    $( "#slider-range" ).slider({
      range: true,
      min: 0,
      max: 150,
      values: [ 0, 150 ],
      slide: function( event, ui ) {
        $( "#amount" ).val(ui.values[ 0 ] + "TL -" + ui.values[ 1 ] + "TL" );
      }
    });
    $( "#amount" ).val($( "#slider-range" ).slider( "values", 0 ) + "TL -" + $( "#slider-range" ).slider( "values", 1 ) + "TL");
  });
  </script>

app/views/listings/show.html.erb
<%= render "shared/navbar" %>
<div id="listings-show">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<%= image_tag @user.image, id: "user_image" %>
			</div>
			<div class="col-md-4">
				<span class="fullname"><%= "#{@user.first_name} #{@user.last_name} " %></span><span id="average_rating"></span> (<%= @user.reviews.count %>)<br>
				<%= "Description: #{@listing.description}" %><br>
				<%= "Lives in: #{@user.location}" %><br>
			</div>
			<div class="col-md-4 booking">	
				<%= "Trial course available: #{@listing.is_trial}" %><br>
				<%= "Price: #{@listing.price} $" %><br>
				<%= "Platform: #{@listing.platform}" %><br>
				
				<% if current_user %>
				<%= link_to "Book Now", new_listing_appointment_path(@listing) ,class: "btn btn-success"  %>
				<%= link_to "Send Message", '#', "data-toggle" => "modal", "data-target" => "#MessageModal",class: "btn btn-danger" %>
				  <div id="MessageModal" class="auth-modal modal" role="dialog">
				    <div class="modal-dialog">

				      <!-- Modal content-->
				      <div class="modal-content"> 
				        <div class="modal-body">
				          <%= form_tag messages_path(to: @user.id), method: :post do %>
				            <div class="form-group">
				              <%= label_tag 'message[subject]', 'Subject' %>
				              <%= text_field_tag 'message[subject]', nil, class: 'form-control', required: true %>
				            </div>

				            <div class="form-group">
				              <%= label_tag 'message[body]', 'Message' %>
				              <%= text_area_tag 'message[body]', nil, cols: 3, class: 'form-control', required: true %>
				            </div>
				            <%= submit_tag 'Send', class: 'btn btn-primary' %>
				          <% end %>      
				        </div>
				        <a href="#" class="modal-close" data-dismiss="modal">X</a>
				      </div>
				    </div>
				  </div> <!-- MessageModal -->
				<% else %>
				<%=  link_to "Book Now", '#', "data-toggle" => "modal", "data-target" => "#ModalSignUp",class: "btn btn-success" %>
				<%= link_to "Send Message", '#', "data-toggle" => "modal", "data-target" => "#ModalSignUp",class: "btn btn-success" %>
				<% end %>
				<br>

			</div>
		</div>
		<div class="row">
			<div class="col-sm-6 col-sm-offset-3">
				<div class="embed-responsive embed-responsive-16by9">
		    		<%= @listing.video_url.html_safe if @listing.video_url %>
				</div>  
			</div>
		</div>
	</div> <!-- container -->

	<div id='calendar'></div>

</div>  <!-- listings-show -->


  <%= render "shared/registration_modals" %>
  <%= render "shared/createEventModal" if current_user %>
<script>
	$('#average_rating').raty({
		path: '',
		readOnly: true,
		score: <%= @user.average_rating %>
	});
  $(document).ready(function() {
var isValidEvent = function(start,end){
    return $("#calendar").fullCalendar('clientEvents', function (event) {
        return (event.rendering === "background" && //Add more conditions here if you only want to check against certain events
                (start.isAfter(event.start) || start.isSame(event.start,'minute')) &&
                (end.isBefore(event.end) || end.isSame(event.end,'minute')));
    }).length > 0;
};
    // page is now ready, initialize the calendar...
    function renderCalendar() {
      $('#calendar').fullCalendar({
        defaultView: 'agendaWeek',
        timezone: 'local',
        contentHeight: 630,
        allDaySlot: false,
        selectable: true,
        slotDuration: '01:00:00',
        scrollTime: '00:00:00',
        events: {
          url: '/users/<%= @listing.user.id %>/timetable'
        },
        dayClick: function(date) {
          console.log('dayClick', date.format());
        },
        eventRender: function(event, el) {
          // render the timezone offset below the event title
          if (event.start.hasZone()) {
            el.find('.fc-title').after(
              $('<div class="tzo"/>').text(event.start.format('Z'))
            );
          }
        },
      select: function(start, end) {
      	 if(isValidEvent(start,end)) {
      	 	start=moment(start).format('YYYY-MM-DDTHH:mm:ssZ');
			end=moment(end).format('YYYY-MM-DDTHH:mm:ssZ');
			var mywhen = start + ' - ' + end;
          $('#createEventModal #apptStartTime').val(start);
          $('#createEventModal #apptEndTime').val(end);
          $('#createEventModal #when').text(mywhen);
          $('#createEventModal').modal('show');
      	}
      	$("#calendar").fullCalendar("unselect");
       },
      selectOverlap: function(event) {
        return ! event.booked;
      }

      });
    }

    renderCalendar();
  });
</script>