config/routes.rb
Rails.application.routes.draw do

devise_for :users,
             path: 'accounts',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                            registrations: 'registrations' }

  get 'users/dashboard'
  
  resources :users, only: [:index] do
    resource :timetable
    resources :listings, only: [:index, :new, :create]
  end

  resources :listings, only: [:show, :edit, :update, :destroy] do 
    resources :appointments, except: [:show]
  end

  resources :appointments, only: [:show] do
    resource :review
  end

  root 'welcome#beta_landing'  
  get 'teacher' => 'welcome#become_a_teacher'
  get 'search' => 'listings#search' 
  get 'nearby' => 'listings#nearby'
  
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  get '/users/:user_id/location', to: 'users#location', as: :user_location

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?       
   
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  acts_as_messageable
  has_many :listings
  has_many :appointments
  has_many :reviews
  has_and_belongs_to_many :languages

  def mailboxer_email(object)
    nil
  end

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user 
      return user
    else
    	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.password = Devise.friendly_token[0,20]
      end
    end
  end 

    def average_rating
      reviews.count == 0 ? 0 : reviews.average(:star).round(2)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = current_user
    @student_appointments = @user.appointments.includes(:listing)
    @teacher_appointments = Appointment.where(listing_id: Listing.where(user_id: current_user.id)).includes(:user)
    @listings = @user.listings.includes(:language)
    @my_students = User.where(id: @teacher_appointments.select(:user_id).distinct)
    @my_teachers = User.where(id: Listing.where(id: @student_appointments.select(:listing_id).distinct).select(:user_id).distinct)
    @hours = ["00:00", "00:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30", "21:00", "21:30", "22:00", "22:30", "23:00", "23:30", "24:00"]
  	@timetable = @user.timetable
    @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end
  end

  def location
      @user = current_user
     @hash = Gmaps4rails.build_markers(@user) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
    end   
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_review_form.html.erb
<%= form_for([s, s.build_review], url: appointment_review_path(s), html: { method: :post }) do |f| %>
	<div class="form-group">
	<%= f.text_field :comment, class: "form-control", placeholder: "comment" %>
	</div>
	<div id="user_stars_<%=s.id%>"></div>				
	<div class="submit-application">
		  <%= f.submit "Submit", class: "btn btn-danger" %>  	
	</div>	  
<% end %>

<script>
	$('#user_stars_<%=s.id%>').raty({
		path: '',
		scoreName: 'review[star]',
		score: 1
	});
</script>

app/views/users/_timetable.html.erb
<table class="table table-bordered" id='timetable'>
    <thead>
      <tr>
         <th></th>
         <th>Sun</th>
         <th>Mon</th>
         <th>Tue</th>
         <th>Wed</th>
         <th>Thu</th>
         <th>Fri</th>
         <th>Sat</th>
      </tr>
    </thead>
    <tbody class="timetable-rows">
  	  <% (0..47).each do |i| %>
	      <tr>
	        <td><%= @hours[i] %></td>
	        <td data-slot='<%=i%>' class='timeslot'></td>	        
	        <td data-slot='<%=i+48%>' class='timeslot'></td>
	        <td data-slot='<%=i+48*2%>' class='timeslot'></td>
	        <td data-slot='<%=i+48*3%>' class='timeslot'></td>
	        <td data-slot='<%=i+48*4%>' class='timeslot'></td>
	        <td data-slot='<%=i+48*5%>' class='timeslot'></td>
	        <td data-slot='<%=i+48*6%>' class='timeslot'></td>
	      </tr>
      <% end %>
      	<tr>
      		<td>24:00</td>
      	</tr>
    </tbody>
  </table>

app/views/users/dashboard.html.erb
<%= render 'shared/navbar' %>

<div id="dashboard">
    <div class="container">
        <div class="row">
            <div id="leftbar" class="col-md-4">
                <div class="leftbar-header clearfix">
                    <div class="userimage">
                        <%= image_tag current_user.image, size: "120x120" %>
                    </div>
                    <h3> <%= current_user.first_name %></h3>
                    <h5> <%= current_user.location %></h5>
                </div>
                <div class="navigation">
                    <ul>
                        <% if current_user.type == "Teacher" %>
                            <strong>Teaching Info</strong>
                            <li data-content='my-listings'>
                                <div class="nav-item">My Listings</div>
                            </li>
                            <li data-content='my-students'>
                                <div class="nav-item">My Students</div>
                            </li>
                            <li data-content='payout'>
                                <div class="nav-item">Payout</div>
                            </li>
                            <li data-content='my-timetable' id='timetable-tab'>
                                <div class="nav-item">My Timetable</div>
                            </li>
                            <% end %>
                                <strong>Student Info</strong>
                                <li data-content='my-lessons'>
                                    <div class="nav-item">My Lessons</div>
                                </li>
                                <li data-content='my-teachers'>
                                    <div class="nav-item">My Teachers</div>
                                </li>
                                <li data-content='payment'>
                                    <div class="nav-item">Payment</div>
                                </li>
                                <li data-content='profile-settings'>
                                    <div class="nav-item">Profile Settings</div>
                                </li>
                    </ul>
                </div>





            </div>
            <div id="dashboard-content" class="col-md-8">

                <div id="my-lessons" class="nav-item-content active">
                    My Lessons
                    <h4> Student Appointments </h4>
                    <% @student_appointments.each do |s| %>
                        <div class="well">
                            <p>Student:
                                <%= current_user.email %>
                            </p>
                            <p>Listind ID:
                                <%= s.listing.id %>
                            </p>
                            <% if s.review %>
                                <p>Your comment:
                                    <%= s.review.comment %>
                                </p>
                                <div id="stars_<%= s.id %>"></div>
                                <div>
                                    <%= s.review.created_at.strftime("%v") %>
                                </div>
                                <% else %>
                                    <%= render 'review_form', s: s %>
                                        <% end %>
                        </div>
                        <script>
                            $('#stars_<%= s.id %>').raty({
                                path: '',
                                readOnly: true,
                                score: <%= s.review.star %>
                            });
                        </script>
                        <% end %>
                            <h4> Teacher Appointments </h4>
                            <% @teacher_appointments.each do |t| %>
                                <p>Student:
                                    <%= t.user.email %>
                                </p>
                                <p>Teacher:
                                    <%= current_user.email %>
                                </p>
                                <% end %>
                </div>

                <div id="my-teachers" class="nav-item-content">
                    My Teacher
                    <% @my_teachers.each do |teacher| %>
                        <p>First Name:
                            <%= teacher.first_name %>
                        </p>
                        <p>Email:
                            <%= teacher.email %>
                        </p>
                        <% end %>
                </div>

                <div id="my-students" class="nav-item-content">
                    My Students
                    <% @my_students.each do |student| %>
                        <p>First Name:
                            <%= student.first_name %>
                        </p>
                        <p>Email:
                            <%= student.email %>
                        </p>
                        <% end %>
                </div>

                <div id="my-listings" class="nav-item-content">
                    My Listings<br>
                    <%= link_to "Create a New Listing", new_user_listing_path(@user), class: "btn btn-success" %>
                        <% @listings.each do |listing| %>
                            <div class="listing-item">
                                <p>Language:
                                    <%= listing.language.name %>
                                </p>
                                <p>Description:
                                    <%= listing.description %>
                                </p>
                                <p>Price:
                                    <%= listing.price %>
                                </p>
                                <%= link_to "Edit Listing", edit_listing_path(listing) %>

                            </div><br>
                            <% end %>
                </div>

                <div id="payout" class="nav-item-content">
                    Payout
                </div>

                <div id="my-timetable" class="nav-item-content">
                    <h1>Edit Your Timetable</h1>
                   <%= form_for(:user, url: registration_path(:user), html: { method: :put }, id: "application") do |f| %>
                        <%= f.hidden_field :timetable, id: 'timetableInput' %>
                        <%= f.submit "Save Timetable", class: "btn btn-success" %>
                    <% end %>
                    <%= render 'timetable' %>
 
                </div>

                <div id="payment" class="nav-item-content">
                    Payment
                </div>

                <div id="profile-settings" class="nav-item-content">
                    Profile Settings
                    <%= link_to "My Location", user_location_path(@user) %>
                    <%= image_tag @user.avatar.url(:thumb) %>
                        <%= form_for(:user, url: registration_path(:user), html: { method: :put }, id: "application") do |f| %>
                            <div class="form-group">
                                <%= f.label :location %>
                                    <%= f.text_field :location, class: "form-control", id: "location" %>
                            </div>
                            <div class="form-group">
                                <%= f.label :phone %>
                                    <%= f.text_field :phone, class: "form-control", id: "phone" %>
                            </div>
                            <div class="form-group">
                                <%= f.label :from %>
                                    <%= f.text_field :from, class: "form-control", id: "from" %>
                            </div>
                            <div class="form-group">
                                <%= f.label :skype %>
                                    <%= f.text_field :skype, class: "form-control", id: "skype" %>
                            </div>
                            <div class="form-group">
                                <%= f.label :time_zone %>
                                    <%= f.time_zone_select :time_zone, nil, {}, {class: "form-control", id: "time_zone"}  %>
                            </div>
                            <div class="submit-application">
                                <%= f.submit "Submit", class: "btn btn-success" %>
                            </div>
                            <% end %>
                            <%= form_for :user, url: registration_path(:user), html: { multipart: true, method: :put } do |form| %>
                              <%= form.file_field :avatar %>
                              <%= form.submit "Submit Photo", class: "btn btn-danger" %>
                            <% end %>
                </div>




            </div>

        </div>

    </div>




</div>

<script>
    $(function() {
        var isMouseDown = false,
            isSelected;
        $("#timetable .timeslot")
            .mousedown(function() {
                isMouseDown = true;
                $(this).toggleClass("selected");
                isSelected = $(this).hasClass("selected");
                return false; // prevent text selection
            })
            .mouseover(function() {
                if (isMouseDown) {
                    $(this).toggleClass("selected", isSelected);
                }
            })
            .bind("selectstart", function() {
                return false;
            })

        $(document)
            .mouseup(function() {
                isMouseDown = false;
            });

        
        $('#timetable').mouseup(function() {
            var timetableArray = Array.apply(null, Array(672)).map(Number.prototype.valueOf,0)
            var a = 0;
            $("td.selected").each(function() {
                a = parseInt($(this).attr('data-slot'));
                timetableArray[a*2] = 1;
                timetableArray[a*2+1] = 1;        
            });
            $('#timetableInput').val(timetableArray.toString().replace(/,/g,''));
        });

        <% if @timetable %>
            <% (0..335).find_all do |i| %>
                <% if @timetable[i*2] == '1' %>
                    $("td[data-slot= <%= i %>]").addClass("selected");
                <% end %>
            <% end %>
        <% end %>





        });
</script>

app/views/users/location.html.erb
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<%= form_for(:user, url: registration_path(:user), html: { method: :put }, id: "application") do |f| %>
    <%= f.hidden_field :latitude, id: 'map_lat' %>
    <%= f.hidden_field :longitude, id: 'map_lng' %>
    <%= f.submit "Save your new location", class: "btn btn-success" %>
<% end %>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<h1><%= @user.first_name %></h1>
<p>Latitude: <%= @user.latitude %></p>
<p>Longitude: <%= @user.longitude %></p>
 <p><%= @user.address %></p>



<script>

$( document ).ready(function() {


function gmap_form(user) {
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });

  var markerOnMap;

  function placeMarker(location) {    // simply method for put new marker on map
    if (markerOnMap) {
      markerOnMap.setPosition(location);
    }
    else {
      markerOnMap = new google.maps.Marker({
        position: location,
        map: handler.getMap()
      });
    }
  }

  google.maps.event.addListener(handler.getMap(), 'click', function(event) {    // event for click-put marker on map and pass coordinates to hidden fields in form
    placeMarker(event.latLng);
    document.getElementById("map_lat").value = event.latLng.lat();
    document.getElementById("map_lng").value = event.latLng.lng();
  });
}


	var user = <%=@user.to_json.html_safe%>;   // pass ruby variable to javascript
    gmap_form(user);    // init show map for user card (only print marker)








    });
</script>