config/routes.rb
Rails.application.routes.draw do

devise_for :users,
             path: 'accounts',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                            registrations: 'registrations' }

  get 'users/dashboard'
  
  resources :users, only: [:index] do
    resource :timetable
    resources :listings, only: [:index, :new, :create]
  end

  resources :listings, only: [:show, :edit, :update, :destroy] do 
    resources :appointments, except: [:show]
  end

  resources :appointments, only: [:show] do
    resource :review
  end

  root 'welcome#beta_landing'  
  get 'teacher' => 'welcome#become_a_teacher'
  get 'search' => 'listings#search' 
  get 'nearby' => 'listings#nearby'
  
  
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

  get '/users/:user_id/location', to: 'users#location', as: :user_location

  

end

app/views/shared/_createEventModal.html.erb
<div id="createEventModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Request an Appointment</h4>
      </div>
      <div class="modal-body">
          <%= form_for [@listing, @appointment] do |f| %>
          <%= f.hidden_field :starts_at, id: "apptStartTime" %>
          <%= f.hidden_field :ends_at, id: "apptEndTime" %>
          <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="control-group">
            <label class="control-label" for="when">When:</label>
            <div class="controls controls-row" id="when">
            </div>
        </div>
          <%= f.submit "Send Request", class: 'btn btn-success' %>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav id="shared-navbar" class="navbar navbar-static-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sharedNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="nav-brand" href="#">PAPIRUS</a>
    </div>
    <div id="sharedNavbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Eğitmen ara", search_path, class:"shared-nav-item" %></li>
          <% if !current_user || (current_user && current_user.type != "Teacher") %>
            <% if(user_signed_in?) %>
              <li><%= link_to "Eğitmen ol", teacher_path, class:"shared-nav-item" %></li>
            <% else %>              
              <li><a href="#" data-toggle="modal" data-target="#ModalLogin" class="shared-nav-item" >Eğitmen ol</a></li>
            <% end %>
          <% end %>
          <% if(!user_signed_in?) %>
            <li><a href="#"  data-toggle="modal" data-target="#ModalSignUp" class="shared-nav-item" >Kayıt ol</a></li>
            <li><a href="#" data-toggle="modal" data-target="#ModalLogin" class="btn-shared-login">Giriş</a></li>
          <% else %>              
            <li><%= link_to "Çıkış", destroy_user_session_path, method: :delete, class:"shared-nav-item" %></li>
          <% end %>
        </ul>
    </div> <!-- sharedNavbar -->
  </div> <!-- container-fluid -->
</nav> <!-- navbar-fixed-top -->

app/views/shared/_registration_modals.html.erb
<!-- Modal -->
  <div id="ModalLogin" class="auth-modal modal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="social-buttons">
          <%= link_to '<i class="fa fa-facebook"></i> Log In with Facebook'.html_safe, user_omniauth_authorize_path(:facebook), class: "btn btn-large btn-facebook" %>
          <%= link_to '<i class="fa fa-google-plus"></i> Log In with Google'.html_safe, user_omniauth_authorize_path(:google_oauth2), class: "btn btn-large btn-google" %>
        </div>  


        <div class="modal-body">
          <div class="or-seperator">
            <span>or</span>
          </div>

          <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <div class="email-row">
              <%= f.text_field :email, class: 'form-control', placeholder: 'Email Address' %>
            </div>
            <div class="password-row">
              <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
            </div>
            <%= f.submit 'Log In', class: 'btn btn-default btn-login' %>
          <% end %>
          <div class="login-switch">
            <span class="">Don’t have an account?</span>
            <a data-dismiss="modal" data-toggle="modal" href="#" data-target="#ModalSignUp" >Sign Up</a> 
          </div>        
        </div>
        <a href="#" class="modal-close" data-dismiss="modal">X</a>
      </div>
    </div>
  </div>  <!-- ModalLogin -->

  <div id="ModalSignUp" class="auth-modal modal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="social-buttons">
          <%= link_to '<i class="fa fa-facebook"></i> Sign Up with Facebook'.html_safe, user_omniauth_authorize_path(:facebook), class: "btn btn-large btn-facebook" %>
          <%= link_to '<i class="fa fa-google-plus"></i> Sign Up with Google'.html_safe, user_omniauth_authorize_path(:google_oauth2), class: "btn btn-large btn-google" %>
        </div>  
        <div class="modal-body">
          <div class="or-seperator">
            <span>or</span>
          </div>
          <%= form_for(:user, :url => registration_path(:user)) do |f| %>
              <div class="email-row">
                <%= f.text_field :email, class: 'form-control', placeholder: 'Email Address' %>
              </div>
              <div class="password-row">
                <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
              </div>
              <div class="password-row password-confirm">
                <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password' %>
              </div>
              <%= f.submit 'Sign Up', class: 'btn btn-default btn-signup' %>
          <% end %>
          <div class="login-switch">
            <span class="">Already a member?</span>
            <a data-dismiss="modal" data-toggle="modal" href="#" data-target="#ModalLogin" >Sign In</a> 
          </div>
        </div>
        <a href="#" class="modal-close" data-dismiss="modal">X</a>
      </div>
    </div>
  </div>  <!-- ModalSignUp -->